"""Equipment registry — what the Isaac twin can actually put on screen.

The twin reads geometry from the Opentrons definition in a run's ledger, so it
will happily *attempt* any labware. That is the problem: substituting the 15 mL
Falcon tube mesh for 1.5 mL Eppendorfs produced tubes towering over a
featureless grey block. It looked authoritative and was wrong.

So this is a whitelist, and anything outside it stops the run before the sim
starts. A refused run tells you exactly what is missing; a fake one does not.

    python -m twin.registry --list            # what is supported
    python -m twin.registry --list-all        # every known Opentrons item
    python -m twin.registry --check ledger.json

twin/registry.json is generated by scripts/build_registry.py from
opentrons_shared_data, so this module needs no Opentrons install — which
matters because it runs inside the Isaac container.
"""
import json
import os
import sys

_HERE = os.path.dirname(os.path.abspath(__file__))
_REG_PATH = os.path.join(_HERE, "registry.json")


def load():
    with open(_REG_PATH) as f:
        return json.load(f)


def check_ledger(analysis):
    """Return (ok, problems, deck). `analysis` is a parsed analysis.json.

    problems is a list of human-readable strings — one per unsupported item.
    """
    reg = load()
    problems, deck = [], []

    # Labware standing on a module is located by moduleId, so resolve it to the
    # module's slot -- otherwise the deck listing reads "slot ?" for every plate
    # on a temperature module.
    mod_slot = {m.get("id"): (m.get("location") or {}).get("slotName")
                for m in analysis.get("modules", [])}

    for lw in analysis.get("labware", []):
        name = lw.get("loadName")
        loc = lw.get("location") or {}
        slot = loc.get("slotName") or mod_slot.get(loc.get("moduleId")) or "?"
        e = reg["labware"].get(name)
        if e is None:
            problems.append(f"slot {slot}: {name} — unknown to this Opentrons version")
        elif e["support"] != "cad":
            problems.append(f"slot {slot}: {name} — {e['note']}")
        else:
            deck.append(f"slot {slot}: {name}")

    for p in analysis.get("pipettes", []):
        name = p.get("pipetteName")
        mount = p.get("mount", "?")
        e = reg["pipettes"].get(name)
        if e is None:
            problems.append(f"{mount} mount: {name} — unknown pipette")
        elif e["support"] != "cad":
            problems.append(f"{mount} mount: {name} — {e['note']}")
        else:
            deck.append(f"{mount} mount: {name}")

    # Modules appear as their own entries, not as labware.
    seen_mod = set()
    for m in analysis.get("modules", []):
        model = m.get("model") or m.get("moduleModel") or "?"
        slot = (m.get("location") or {}).get("slotName", "?")
        seen_mod.add(model)
        e = reg["modules"].get(model)
        if e is None:
            problems.append(f"slot {slot}: module {model} — unknown module")
        elif e["support"] != "cad":
            problems.append(f"slot {slot}: module {model} — {e['note']}")
        else:
            deck.append(f"slot {slot}: module {model} ({e['display']})")
    for c in analysis.get("commands", []):
        if c.get("commandType") == "loadModule":
            model = (c.get("params") or {}).get("model", "?")
            if model in seen_mod:
                continue
            e = reg["modules"].get(model)
            if e is None or e["support"] != "cad":
                problems.append(f"module {model} — "
                                f"{(e or {}).get('note', 'unknown module')}")

    return (not problems), problems, deck


def supported_lines():
    reg = load()
    out = ["SUPPORTED LABWARE"]
    for n, e in sorted(reg["labware"].items()):
        if e["support"] == "cad":
            out.append(f"  {n:<44} {e['note']}")
    out.append("")
    out.append("SUPPORTED PIPETTES")
    for n, e in sorted(reg["pipettes"].items()):
        if e["support"] == "cad":
            out.append(f"  {n:<44} {e['note']}")
    out.append("")
    out.append("SUPPORTED MODULES")
    for n, e in sorted(reg["modules"].items()):
        if e["support"] == "cad":
            out.append(f"  {n:<44} {e['note']}")
    return out


def _all_lines():
    reg = load()
    out = [f"Opentrons data version: {reg['opentrons_version']}", ""]
    for section in ("labware", "pipettes", "modules"):
        items = reg[section]
        ok = sum(1 for e in items.values() if e["support"] == "cad")
        out.append(f"{section.upper()}  ({ok} supported / {len(items)} known)")
        for n, e in sorted(items.items()):
            mark = "OK " if e["support"] == "cad" else "-- "
            out.append(f"  {mark}{n:<48} {e['note']}")
        out.append("")
    return out


def main(argv):
    if "--list-all" in argv:
        print("\n".join(_all_lines()))
        return 0
    if "--check" in argv:
        path = argv[argv.index("--check") + 1]
        with open(path) as f:
            ok, problems, deck = check_ledger(json.load(f))
        if ok:
            print("EQUIPMENT OK — every item is modelled:")
            for d in deck:
                print("   ", d)
            return 0
        print("RUN REFUSED — this protocol uses equipment the twin cannot render:")
        for p in problems:
            print("   x", p)
        print()
        print("Rendering it anyway would substitute the wrong geometry (e.g. 15 mL")
        print("Falcon tubes for 1.5 mL Eppendorfs) and show you a run that is not")
        print("the one you wrote.")
        print()
        print("\n".join(supported_lines()))
        return 2
    print("\n".join(supported_lines()))
    return 0


if __name__ == "__main__":
    sys.exit(main(sys.argv[1:]))
