requirements = {"robotType": "OT-2"}
from opentrons import protocol_api

metadata = {
    "protocolName": "MIC of Olive Leaf Extract against L. monocytogenes F2365",
    "author": "paper2protocol",
    "description": (
        "Two-fold broth microdilution MIC assay, replicating "
        "Liu et al., PLOS ONE 17(1):e0263359 (2022), doi:10.1371/journal.pone.0263359. "
        "Eight OLE concentrations (128-1 mg/mL) by two-fold serial dilution in BHI broth; "
        "50 uL OLE + 50 uL of a 1:1000-diluted overnight culture per well (100 uL total); "
        "eight replicates per concentration, plus OLE-only, positive and negative controls."
    ),
    "apiLevel": "2.12",
}

# ---------------------------------------------------------------------------
# FROM THE PAPER (Materials and methods -> "Inhibitory assays of OLE against
# L. monocytogenes"), quoted:
#   "eight OLE concentrations (128.0, 64.0, 32.0, 16.0, 8.0, 4.0, 2.0, and
#    1.0 mg/ml) were generated by two-fold serial dilutions using BHI broth.
#    Fifty microliters (50 uL) of OLE at each concentration and 50 uL of
#    diluted L. monocytogenes F2365 overnight culture, total 100 uL, were
#    mixed into each well of the plate."
#   "Eight replicates (on the plate) were set up for each OLE concentration."
#   "A 1:1000 dilution of the overnight culture with BHI broth was used."
# Controls required by the paper's Eq 1 (inhibitory rate):
#   PC = culture only, NC = BHI only, OLE = OLE only at each concentration.
#
# IMPLEMENTATION DECISIONS (NOT stated in the paper — flagged for sign-off):
#   * The paper does not give the physical volumes used to build the dilution
#     series. We use equal-volume steps of 700 uL in 15 mL conical tubes, which
#     leaves >=450 uL per concentration (9 x 50 uL) after passing 700 uL on.
#   * Plate layout (columns 1-8 = the 8 concentrations, 9 = OLE-only,
#     10 = PC, 11 = NC) is ours; the paper states replicate count only.
#   * Fresh tip on every liquid change to prevent carryover.
# ---------------------------------------------------------------------------

OLE_CONCENTRATIONS = [128.0, 64.0, 32.0, 16.0, 8.0, 4.0, 2.0, 1.0]  # mg/mL
ASSAY_VOL = 50.0          # uL of each component per well -> 100 uL total
N_REPLICATES = 8          # rows A-H
SERIES_VOL = 700.0        # uL per two-fold dilution step (implementation choice)

# tube-rack positions holding the dilution series, highest -> lowest
SERIES_TUBES = ["A1", "A2", "A3", "A4", "A5", "B1", "B2", "B3"]
BHI_TUBE = "B4"           # sterile BHI broth (diluent + controls)
CULTURE_TUBE = "B5"       # 1:1000 diluted overnight culture

ROWS = ["A", "B", "C", "D", "E", "F", "G", "H"]
COL_OLE_ONLY = 9          # OLE at each concentration + BHI (no bacteria)
COL_PC = 10               # positive control: BHI + culture
COL_NC = 11               # negative control: BHI only


def run(protocol: protocol_api.ProtocolContext):
    # ---------------- labware ----------------
    plate = protocol.load_labware("corning_96_wellplate_360ul_flat", "1")
    rack = protocol.load_labware("opentrons_15_tuberack_falcon_15ml_conical", "2")
    tips = protocol.load_labware("opentrons_96_tiprack_300ul", "7")
    p300 = protocol.load_instrument("p300_single_gen2", "left", tip_racks=[tips])

    p300.well_bottom_clearance.aspirate = 1
    p300.well_bottom_clearance.dispense = 1

    bhi = rack[BHI_TUBE]
    culture = rack[CULTURE_TUBE]
    series = [rack[t] for t in SERIES_TUBES]

    ###########################################################################
    # Phase 1 - build the two-fold dilution series in BHI broth.
    # Tube A1 is preloaded by the operator with OLE at 128 mg/mL.
    ###########################################################################
    # 1a. diluent into the seven downstream tubes
    p300.pick_up_tip()
    for tube in series[1:]:
        remaining = SERIES_VOL
        while remaining > 0:
            v = min(remaining, p300.max_volume)
            p300.aspirate(v, bhi)
            p300.dispense(v, tube)
            remaining -= v
    p300.drop_tip()

    # 1b. serial two-fold transfer, fresh tip each step (carryover would bias
    #     every downstream concentration)
    for i in range(len(series) - 1):
        p300.pick_up_tip()
        remaining = SERIES_VOL
        while remaining > 0:
            v = min(remaining, p300.max_volume)
            p300.aspirate(v, series[i])
            p300.dispense(v, series[i + 1])
            remaining -= v
        p300.mix(3, 200, series[i + 1])
        p300.drop_tip()

    ###########################################################################
    # Phase 2 - 50 uL of OLE at each concentration into its column (8 replicate
    # rows) and into the matching OLE-only control well.
    ###########################################################################
    for idx, tube in enumerate(series):
        column = idx + 1                       # column 1 = 128 mg/mL ... 8 = 1.0
        p300.pick_up_tip()
        for row in ROWS:                       # the 8 replicates
            p300.aspirate(ASSAY_VOL, tube)
            p300.dispense(ASSAY_VOL, plate[f"{row}{column}"])
        # OLE-only control for this concentration (one well, row = concentration)
        p300.aspirate(ASSAY_VOL, tube)
        p300.dispense(ASSAY_VOL, plate[f"{ROWS[idx]}{COL_OLE_ONLY}"])
        p300.drop_tip()

    ###########################################################################
    # Phase 3 - BHI broth into the control wells.
    #   OLE-only : 50 uL BHI  (replaces the culture)
    #   NC       : 100 uL BHI (both components)
    #   PC       : 50 uL BHI  (replaces the OLE)
    ###########################################################################
    p300.pick_up_tip()
    for idx in range(len(OLE_CONCENTRATIONS)):
        p300.aspirate(ASSAY_VOL, bhi)
        p300.dispense(ASSAY_VOL, plate[f"{ROWS[idx]}{COL_OLE_ONLY}"])
    for row in ROWS:
        p300.aspirate(ASSAY_VOL, bhi)
        p300.dispense(ASSAY_VOL, plate[f"{row}{COL_PC}"])
    for row in ROWS:                            # NC gets BHI for both halves
        p300.aspirate(ASSAY_VOL, bhi)
        p300.dispense(ASSAY_VOL, plate[f"{row}{COL_NC}"])
        p300.aspirate(ASSAY_VOL, bhi)
        p300.dispense(ASSAY_VOL, plate[f"{row}{COL_NC}"])
    p300.drop_tip()

    ###########################################################################
    # Phase 4 - 50 uL of the 1:1000 diluted overnight culture into every
    # experimental well and into the positive controls. NC and OLE-only get
    # none, by design.
    ###########################################################################
    p300.pick_up_tip()
    for column in range(1, len(OLE_CONCENTRATIONS) + 1):
        for row in ROWS:
            p300.aspirate(ASSAY_VOL, culture)
            p300.dispense(ASSAY_VOL, plate[f"{row}{column}"])
    for row in ROWS:
        p300.aspirate(ASSAY_VOL, culture)
        p300.dispense(ASSAY_VOL, plate[f"{row}{COL_PC}"])
    p300.drop_tip()

    ###########################################################################
    # Handoff gate - outside a liquid handler's scope.
    ###########################################################################
    protocol.comment(
        "HANDOFF: incubate 24 h at 37 C, then read OD600 on a microplate reader "
        "at 37 C with 0.05 linear agitation (paper: BioTek, Gen5 v3.00.19)."
    )
